### ISSUE TITLE
interface{} does not implement comparable [InvalidTypeArg]

### ISSUE THREAD

**Issue by hughjfchen** [TeaEntityLab/fpGo#1]
I've been just trying to explore FP in go and found this. I tried to open the code but met following error:
`interface{} does not implement comparable [InvalidTypeArg]`

The code has such an error is in `stream.go`:
`// StreamFromInterface New Stream instance from an array
func StreamFromInterface(list ...interface{}) *StreamDef[interface{}] {
    return StreamFromArray(list)
}`
Line 17 to line 21

I'm using go 1.18 on MacOs 12.3

**Comment by johnteee** [comment]
@hughjfchen 
After considering about functionalities,
finally I add back the non-generics version of Stream/Set/StreamSet etc.

I tested it and released it on v2.1.0

More examples are here
https://github.com/TeaEntityLab/fpGo/blob/master/streamForInterface_test.go

Thanks for your advices!!
