### ISSUE TITLE
Is this an example of Go supporting Haskel concepts? I am interested in functional Go programming and generics

### ISSUE THREAD

**Issue by shehackedyou** [TeaEntityLab/fpGo#3]
Esp bc I keep seeing a lot of hate so they must be interesting.

**Comment by johnteee** [comment]
> Esp bc I keep seeing a lot of hate so they must be interesting.

Yeah, it's right.
There're many concepts from Haskel/Erlang/Akka etc functional programming languages in this library.
BTW the original goal is for general usages 😄 so I just implemented something simple and useful FP features

Thanks for comments 😃
